//! Hot-exit backups: unsaved buffer contents written to the config dir so
//! quitting never loses work. Backups are UTF-8 regardless of the
//! document's target encoding — they only feed the in-memory buffer.

use std::path::{Path, PathBuf};
use tauri::{AppHandle, Manager, Runtime};

/// Backup names are generated by the frontend; reject anything that could
/// escape the backups directory.
fn valid_name(name: &str) -> bool {
    !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
        && !name.starts_with('.')
}

fn backups_dir<R: Runtime>(app: &AppHandle<R>) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_config_dir()
        .map_err(|e| format!("Cannot resolve config dir: {e}"))?;
    Ok(dir.join("backups"))
}

fn write_backup(dir: &Path, name: &str, content: &str) -> Result<(), String> {
    if !valid_name(name) {
        return Err(format!("Invalid backup name: {name}"));
    }
    std::fs::create_dir_all(dir).map_err(|e| format!("Cannot create backups dir: {e}"))?;
    crate::atomic_write(&dir.join(name), content.as_bytes())
        .map_err(|e| format!("Failed to write backup: {e}"))
}

fn read_backup(dir: &Path, name: &str) -> Option<String> {
    if !valid_name(name) {
        return None;
    }
    let bytes = std::fs::read(dir.join(name)).ok()?;
    String::from_utf8(bytes).ok()
}

fn remove_backup(dir: &Path, name: &str) {
    if valid_name(name) {
        let _ = std::fs::remove_file(dir.join(name));
    }
}

#[tauri::command]
pub fn save_backup<R: Runtime>(
    app: AppHandle<R>,
    name: String,
    content: String,
) -> Result<(), String> {
    write_backup(&backups_dir(&app)?, &name, &content)
}

#[tauri::command]
pub fn load_backup<R: Runtime>(app: AppHandle<R>, name: String) -> Option<String> {
    read_backup(&backups_dir(&app).ok()?, &name)
}

#[tauri::command]
pub fn delete_backup<R: Runtime>(app: AppHandle<R>, name: String) {
    if let Ok(dir) = backups_dir(&app) {
        remove_backup(&dir, &name);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn rejects_path_traversal_names() {
        assert!(!valid_name("../evil"));
        assert!(!valid_name("a/b"));
        assert!(!valid_name(".hidden"));
        assert!(!valid_name(""));
        assert!(valid_name("bk-3-1718000000.txt"));
    }

    #[test]
    fn backup_round_trip_and_delete() {
        let dir = std::env::temp_dir().join("plume-backup-test");
        let _ = std::fs::remove_dir_all(&dir);

        write_backup(&dir, "bk-1.txt", "未儲存的內容\nwith two lines").unwrap();
        assert_eq!(
            read_backup(&dir, "bk-1.txt").as_deref(),
            Some("未儲存的內容\nwith two lines")
        );

        remove_backup(&dir, "bk-1.txt");
        assert!(read_backup(&dir, "bk-1.txt").is_none());
        assert!(write_backup(&dir, "../escape", "x").is_err());
        std::fs::remove_dir_all(&dir).ok();
    }
}
